[package]
name = "hello"
version = "0.1.0"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.2"
ark-ec = { version = "0.3.0", features = [ "parallel" ] }
ark-bls12-377 = { version = "0.3.0" }
num-traits = "*"